name = "mafs"
version = "0.0.1"

description = "A high performance maths library for Gleam with performance at the forefront"
licences = ["Apache-2.0"]
repository = { type = "github", user = "versecafe", repo = "mafs" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
